version: '2'
networks:
  private:
services:
 db:
  image: mongo:3.4
  volumes:
    - /data/db:/data/db
  networks:
    - private
  ports:
    - 27017:27017
 is-mutant-service:
  build: ./is-mutant
  ports:
  - 8080:8080
  depends_on:
   - "db"
  networks:
   - private
  links:
    - db
  restart: always
